#!/usr/bin/env python3
"""SPICE サブサーキットネットリスト -> IRSIM .sim 変換（階層フラット化）

  usage: python3 scripts/spi2sim.py spice/REG4x16_src.spi REG4x16 > irsim/reg4x16.sim

LVS ソースネットリスト（LVS クリーン）をそのまま IRSIM に持ち込むための変換。
レイアウト抽出ではないので配線容量は入らないが、トランジスタの接続・寸法は
実物と一致している（LVS が通っているため）。

出力フォーマット（TR-1um_Async_I2C/irsim/*.sim と同じ）:

    | units: 100 tech: scmos
    <n|p><TAB><gate><TAB><source><TAB><drain><TAB><L><TAB><W>

  - L / W は um。TR-1um.prm の resistance テーブル（3.40 / 10.20, L=1.00）と同じ単位。
  - 電源ノードは IRSIM が既定で探す名前 **Vdd / Gnd** に改名する。
  - 階層は `インスタンス名.ノード名` で連結（例 XDEC2_0.RDBE）。
  - `ADD[0]` のような角括弧は IRSIM のコマンド行で扱いにくいので `ADD0` に潰す。
"""
from __future__ import annotations
import re, sys

VDD_NAMES = {"vdd", "vcc"}
GND_NAMES = {"vss", "gnd"}


def sanitize(n: str) -> str:
    """角括弧を潰す。ADD[0] -> ADD0"""
    return n.replace("[", "").replace("]", "")


def parse(path):
    """{サブサーキット名: (ピン列, [M...], [X...])} を返す。継続行 '+' に対応。"""
    lines = []
    for ln in open(path, encoding="utf-8"):
        ln = ln.split("*")[0].rstrip() if ln.lstrip().startswith("*") else ln.rstrip()
        if not ln.strip():
            continue
        if ln.lstrip().startswith("+") and lines:
            lines[-1] += " " + ln.lstrip()[1:].strip()
        else:
            lines.append(ln)

    subs, cur, name = {}, None, None
    for ln in lines:
        t = ln.split()
        if not t or t[0].startswith("*"):
            continue
        low = t[0].lower()
        if low == ".subckt":
            name = t[1]
            cur = {"pins": t[2:], "mos": [], "inst": []}
            subs[name] = cur
            continue
        if low.startswith(".ends"):
            cur = None
            continue
        if cur is None:
            continue
        if low.startswith("m"):
            # M<name> D G S B <model> W=..u L=..u
            d, g, s, b, model = t[1], t[2], t[3], t[4], t[5].upper()
            kv = {}
            for x in t[6:]:
                if "=" in x:
                    k, v = x.split("=", 1)
                    kv[k.upper()] = float(v.rstrip("uU"))
            cur["mos"].append((t[0], model, d, g, s, b, kv.get("W", 0.0), kv.get("L", 0.0)))
        elif low.startswith("x"):
            cur["inst"].append((t[0], t[-1], t[1:-1]))   # 名前, サブ名, 接続ネット
    return subs


def flatten(subs, top):
    """top を再帰的に展開して (種別, gate, source, drain, L, W) のリストを返す。"""
    out = []

    def walk(subname, prefix, netmap):
        sub = subs[subname]

        def n(node):
            if node in netmap:                      # ピン -> 親のネット
                return netmap[node]
            if node.lower() in VDD_NAMES:
                return "Vdd"
            if node.lower() in GND_NAMES:
                return "Gnd"
            return prefix + node                    # 内部ノード

        for _, model, d, g, s, _b, w, l in sub["mos"]:
            kind = "p" if model.startswith("P") else "n"
            out.append((kind, n(g), n(s), n(d), l, w))

        for iname, isub, nets in sub["inst"]:
            child = subs[isub]
            if len(nets) != len(child["pins"]):
                sys.exit(f"ピン数不一致: {iname} ({isub}) {len(nets)} != {len(child['pins'])}")
            walk(isub, prefix + iname + ".", {p: n(a) for p, a in zip(child["pins"], nets)})

    # トップのピンは、そのまま（角括弧だけ潰した）名前で外に出す。
    # 電源だけは IRSIM の既定名にする。
    def toppin(p):
        if p.lower() in VDD_NAMES:
            return "Vdd"
        if p.lower() in GND_NAMES:
            return "Gnd"
        return sanitize(p)

    walk(top, "", {p: toppin(p) for p in subs[top]["pins"]})
    return out


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    src, top = sys.argv[1], sys.argv[2]
    subs = parse(src)
    if top not in subs:
        sys.exit(f"{top} が {src} に見つかりません。候補: {', '.join(subs)}")
    devs = flatten(subs, top)

    w = sys.stdout.write
    w("| units: 100 tech: scmos\n")
    w(f"| generated by scripts/spi2sim.py from {src} (top = {top})\n")
    w("| LVS ソースネットリスト（LVS クリーン）をフラット化したもの。\n")
    w("| 電源は IRSIM の既定名 Vdd / Gnd。角括弧は潰してある（ADD[0] -> ADD0）。\n")
    w("| 配線容量は含まない（.sim に配線形状を持たせていないため）。\n")
    for kind, g, s, d, l, wid in devs:
        w(f"{kind}\t{g}\t{s}\t{d}\t{l:g}\t{wid:g}\n")

    np_ = sum(1 for x in devs if x[0] == "p")
    nn = len(devs) - np_
    print(f"| {len(devs)} transistors  (p {np_} / n {nn})", file=sys.stderr)
    nodes = {x[1] for x in devs} | {x[2] for x in devs} | {x[3] for x in devs}
    print(f"| {len(nodes)} nodes", file=sys.stderr)


if __name__ == "__main__":
    main()
